version: "3"
services:
  server:
    image: 140023361867.dkr.ecr.us-east-1.amazonaws.com/bia:${TAG}
    ports:
      - 80:8080
    environment:
      DB_USER: postgres
      DB_PWD: SENHA
      DB_HOST: bia.clkakwimkm5g.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_SECRET_NAME: rds!db-bb0d65ef-4012-468e-8f96-2cc3e79ca201
      DB_REGION: us-east-1
      # AWS_ACCESS_KEY_ID: 
      # AWS_SECRET_ACCESS_KEY:
      DEBUG_SECRET: true
      # IS_LOCAL: true 
