version: "3"
services:
  server:
    image: 140023361867.dkr.ecr.us-east-1.amazonaws.com/bia:${TAG}
    ports:
      - 80:8080
    environment:
      DB_USER: postgres
      DB_PWD: yOxsznGHZWJ7CNG3PCA4
      DB_HOST: bia.clkakwimkm5g.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
