version: "3"
services:
  server:
    build: .
    ports:
      - 80:8080
    environment:
      DB_USER: postgres
      DB_PWD: yOxsznGHZWJ7CNG3PCA4
      DB_HOST: bia.clkakwimkm5g.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
