name: bia-eb
services:
  server:
    environment:
      DB_HOST: database
      DB_PORT: "5432"
      DB_PWD: postgres
      DB_USER: postgres
    image: 140023361867.dkr.ecr.us-east-1.amazonaws.com/bia:37a2014
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "80"
        protocol: tcp
networks:
  default:
    name: bia-eb_default
